/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as BecomeAHostRouteImport } from './routes/become-a-host'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PassRsvpIdRouteImport } from './routes/pass.$rsvpId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HSlugRouteImport } from './routes/h.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardEventsIdIndexRouteImport } from './routes/dashboard.events.$id.index'
import { Route as DashboardEventsIdOutcomesRouteImport } from './routes/dashboard.events.$id.outcomes'
import { Route as DashboardEventsIdGalleryRouteImport } from './routes/dashboard.events.$id.gallery'
import { Route as DashboardEventsIdCheckersRouteImport } from './routes/dashboard.events.$id.checkers'
import { Route as DashboardEventsIdCheckInRouteImport } from './routes/dashboard.events.$id.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAHostRoute = BecomeAHostRouteImport.update({
  id: '/become-a-host',
  path: '/become-a-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PassRsvpIdRoute = PassRsvpIdRouteImport.update({
  id: '/pass/$rsvpId',
  path: '/pass/$rsvpId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugRoute = HSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdIndexRoute = DashboardEventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEventsIdRoute,
} as any)
const DashboardEventsIdOutcomesRoute =
  DashboardEventsIdOutcomesRouteImport.update({
    id: '/outcomes',
    path: '/outcomes',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdGalleryRoute =
  DashboardEventsIdGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdCheckersRoute =
  DashboardEventsIdCheckersRouteImport.update({
    id: '/checkers',
    path: '/checkers',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdCheckInRoute =
  DashboardEventsIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/e/$slug': typeof ESlugRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pass/$rsvpId': typeof PassRsvpIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard/events/$id/checkers': typeof DashboardEventsIdCheckersRoute
  '/dashboard/events/$id/gallery': typeof DashboardEventsIdGalleryRoute
  '/dashboard/events/$id/outcomes': typeof DashboardEventsIdOutcomesRoute
  '/dashboard/events/$id/': typeof DashboardEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/check-in': typeof CheckInRoute
  '/events': typeof EventsRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/e/$slug': typeof ESlugRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pass/$rsvpId': typeof PassRsvpIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard/events/$id/checkers': typeof DashboardEventsIdCheckersRoute
  '/dashboard/events/$id/gallery': typeof DashboardEventsIdGalleryRoute
  '/dashboard/events/$id/outcomes': typeof DashboardEventsIdOutcomesRoute
  '/dashboard/events/$id': typeof DashboardEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/e/$slug': typeof ESlugRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pass/$rsvpId': typeof PassRsvpIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/$id/check-in': typeof DashboardEventsIdCheckInRoute
  '/dashboard/events/$id/checkers': typeof DashboardEventsIdCheckersRoute
  '/dashboard/events/$id/gallery': typeof DashboardEventsIdGalleryRoute
  '/dashboard/events/$id/outcomes': typeof DashboardEventsIdOutcomesRoute
  '/dashboard/events/$id/': typeof DashboardEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-host'
    | '/check-in'
    | '/dashboard'
    | '/events'
    | '/my-events'
    | '/tickets'
    | '/dashboard/reports'
    | '/e/$slug'
    | '/h/$slug'
    | '/invite/$token'
    | '/pass/$rsvpId'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/events/$id/check-in'
    | '/dashboard/events/$id/checkers'
    | '/dashboard/events/$id/gallery'
    | '/dashboard/events/$id/outcomes'
    | '/dashboard/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-host'
    | '/check-in'
    | '/events'
    | '/my-events'
    | '/tickets'
    | '/dashboard/reports'
    | '/e/$slug'
    | '/h/$slug'
    | '/invite/$token'
    | '/pass/$rsvpId'
    | '/dashboard'
    | '/dashboard/events/new'
    | '/dashboard/events/$id/check-in'
    | '/dashboard/events/$id/checkers'
    | '/dashboard/events/$id/gallery'
    | '/dashboard/events/$id/outcomes'
    | '/dashboard/events/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/become-a-host'
    | '/check-in'
    | '/dashboard'
    | '/events'
    | '/my-events'
    | '/tickets'
    | '/dashboard/reports'
    | '/e/$slug'
    | '/h/$slug'
    | '/invite/$token'
    | '/pass/$rsvpId'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/events/$id/check-in'
    | '/dashboard/events/$id/checkers'
    | '/dashboard/events/$id/gallery'
    | '/dashboard/events/$id/outcomes'
    | '/dashboard/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BecomeAHostRoute: typeof BecomeAHostRoute
  CheckInRoute: typeof CheckInRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  MyEventsRoute: typeof MyEventsRoute
  TicketsRoute: typeof TicketsRoute
  ESlugRoute: typeof ESlugRoute
  HSlugRoute: typeof HSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PassRsvpIdRoute: typeof PassRsvpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-host': {
      id: '/become-a-host'
      path: '/become-a-host'
      fullPath: '/become-a-host'
      preLoaderRoute: typeof BecomeAHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/pass/$rsvpId': {
      id: '/pass/$rsvpId'
      path: '/pass/$rsvpId'
      fullPath: '/pass/$rsvpId'
      preLoaderRoute: typeof PassRsvpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug': {
      id: '/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof HSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id/': {
      id: '/dashboard/events/$id/'
      path: '/'
      fullPath: '/dashboard/events/$id/'
      preLoaderRoute: typeof DashboardEventsIdIndexRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/outcomes': {
      id: '/dashboard/events/$id/outcomes'
      path: '/outcomes'
      fullPath: '/dashboard/events/$id/outcomes'
      preLoaderRoute: typeof DashboardEventsIdOutcomesRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/gallery': {
      id: '/dashboard/events/$id/gallery'
      path: '/gallery'
      fullPath: '/dashboard/events/$id/gallery'
      preLoaderRoute: typeof DashboardEventsIdGalleryRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/checkers': {
      id: '/dashboard/events/$id/checkers'
      path: '/checkers'
      fullPath: '/dashboard/events/$id/checkers'
      preLoaderRoute: typeof DashboardEventsIdCheckersRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/check-in': {
      id: '/dashboard/events/$id/check-in'
      path: '/check-in'
      fullPath: '/dashboard/events/$id/check-in'
      preLoaderRoute: typeof DashboardEventsIdCheckInRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
  }
}

interface DashboardEventsIdRouteChildren {
  DashboardEventsIdCheckInRoute: typeof DashboardEventsIdCheckInRoute
  DashboardEventsIdCheckersRoute: typeof DashboardEventsIdCheckersRoute
  DashboardEventsIdGalleryRoute: typeof DashboardEventsIdGalleryRoute
  DashboardEventsIdOutcomesRoute: typeof DashboardEventsIdOutcomesRoute
  DashboardEventsIdIndexRoute: typeof DashboardEventsIdIndexRoute
}

const DashboardEventsIdRouteChildren: DashboardEventsIdRouteChildren = {
  DashboardEventsIdCheckInRoute: DashboardEventsIdCheckInRoute,
  DashboardEventsIdCheckersRoute: DashboardEventsIdCheckersRoute,
  DashboardEventsIdGalleryRoute: DashboardEventsIdGalleryRoute,
  DashboardEventsIdOutcomesRoute: DashboardEventsIdOutcomesRoute,
  DashboardEventsIdIndexRoute: DashboardEventsIdIndexRoute,
}

const DashboardEventsIdRouteWithChildren =
  DashboardEventsIdRoute._addFileChildren(DashboardEventsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRouteWithChildren
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsIdRoute: DashboardEventsIdRouteWithChildren,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BecomeAHostRoute: BecomeAHostRoute,
  CheckInRoute: CheckInRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  MyEventsRoute: MyEventsRoute,
  TicketsRoute: TicketsRoute,
  ESlugRoute: ESlugRoute,
  HSlugRoute: HSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  PassRsvpIdRoute: PassRsvpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
